auth:
  password: redis
master:
  persistence:
    size: 2Gi
  resources:
    requests:
      memory: 2Gi
      cpu: 1
replica:
  replicaCount: 1
  persistence:
    size: 2Gi
  resources:
    requests:
      memory: 2Gi
      cpu: 1